/**
 * MenuBackdrop (Workstream 10.2) — a cheap procedural animated backdrop for
 * the main menu, standing in for a live 3D flythrough (deferred: booting the
 * actual WebGPU world behind the menu costs ~48s, see PROGRESS.md M8 — far
 * too slow for a menu, and the LAAS engine dirs are off-limits to this
 * slice). Three parallax hill-silhouette layers, each an SVG polygon whose
 * ridge is generated by `domain/presentation/Skyline` from a fixed seed, laid
 * out twice side-by-side and drifted left via a CSS animation so the tile
 * loops seamlessly. Purely presentational: no canvas, no rAF loop — CSS
 * `@keyframes` already respect `prefers-reduced-motion` / the reducedMotion
 * setting through the global rule in `styles.ts`, so a static backdrop is
 * free for those users.
 */

import { generateSkyline } from "../../domain/presentation/Skyline";
import { injectStyles } from "../styles";

const SEGMENTS = 10;
const LAYER_COLORS = ["var(--lw-bg-track)", "var(--lw-border)", "var(--lw-bg-panel)"] as const;
const LAYER_SPEEDS_S = [90, 60, 40] as const; // nearest layer drifts fastest

function ridgePath(heights: readonly number[]): string {
  // two tiles side by side (0..1 and 1..2 of the viewBox width) so a -50%
  // translate loops with no visible seam
  const points: string[] = ["0,1"];
  const n = heights.length - 1; // last point mirrors the first (closed loop)
  for (let tile = 0; tile < 2; tile++) {
    for (let i = 0; i <= n; i++) {
      const x = tile + i / n;
      const y = 1 - heights[i];
      points.push(`${x},${y}`);
    }
  }
  points.push("2,1");
  return points.join(" ");
}

export function MenuBackdrop(seed: number, opts: { doc?: Document } = {}): HTMLElement {
  const doc = opts.doc ?? document;
  injectStyles(doc);

  const root = doc.createElement("div");
  root.className = "laas-ui lw-menu-backdrop";
  root.setAttribute("aria-hidden", "true");

  const layers = generateSkyline(seed, LAYER_COLORS.length, SEGMENTS);
  const svgNs = "http://www.w3.org/2000/svg";
  for (let i = 0; i < layers.length; i++) {
    const wrap = doc.createElement("div");
    wrap.className = "lw-menu-backdrop-layer";
    wrap.style.animationDuration = `${LAYER_SPEEDS_S[i]}s`;

    const svg = doc.createElementNS(svgNs, "svg");
    svg.setAttribute("viewBox", "0 0 2 1");
    svg.setAttribute("preserveAspectRatio", "none");
    svg.setAttribute("width", "200%");
    svg.setAttribute("height", "100%");

    const poly = doc.createElementNS(svgNs, "polygon");
    poly.setAttribute("points", ridgePath(layers[i].heights));
    poly.setAttribute("fill", LAYER_COLORS[i]);
    svg.appendChild(poly);
    wrap.appendChild(svg);
    root.appendChild(wrap);
  }

  return root;
}
